# permissions for end users to view agentserviceconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentserviceconfig-viewer-role
rules:
- apiGroups:
  - agent-install.openshift.io
  resources:
  - agentserviceconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - agent-install.openshift.io
  resources:
  - agentserviceconfigs/status
  verbs:
  - get
