# permissions for end users to edit agentserviceconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agentserviceconfig-editor-role
rules:
- apiGroups:
  - agent-install.openshift.io
  resources:
  - agentserviceconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agent-install.openshift.io
  resources:
  - agentserviceconfigs/status
  verbs:
  - get
